### ISSUE TITLE
Error data.table for chunks with different columns  : Error in rbindlist(res, use.names = use.names, fill = fill, idcol = idcol)

### ISSUE THREAD

**Issue by palamito** [xiaodaigh/disk.frame#296] opened 2020-07-09 06:40 UTC
I am encountering an error while using data.table to filtering a disk.frame when, for inadvertance, two chunks have different columns. For example, let's say I have a two chunks with 4 columns, but 1 of them has a different name (`Factor` in `chunk1` and `Character` in `chunk2`) :

```r
nr_of_rows <- 1e2

chunk1 <- data.frame(
  Logical = sample(c(TRUE, FALSE, NA), prob = c(0.85, 0.1, 0.05), nr_of_rows, replace = TRUE),
  Integer = sample(1L:100L, nr_of_rows, replace = TRUE),
  Real = sample(sample(1:10000, 20) / 100, nr_of_rows, replace = TRUE),
  Factor = as.factor(sample(labels(UScitiesD), nr_of_rows, replace = TRUE))
)

chunk2 <- data.frame(
  Logical = sample(c(TRUE, FALSE, NA), prob = c(0.85, 0.1, 0.05), nr_of_rows, replace = TRUE),
  Integer = sample(1L:100L, nr_of_rows, replace = TRUE),
  Real = sample(sample(1:10000, 20) / 100, nr_of_rows, replace = TRUE),
  Character = sample(labels(UScitiesD), nr_of_rows, replace = TRUE)
)
```

I then build a disk.frame with the two chunks :

```r
library(disk.frame)
# this willl set disk.frame with multiple workers
setup_disk.frame()
# this will allow unlimited amount of data to be passed from worker to worker
options(future.globals.maxSize = Inf)

main.disk.frame <- disk.frame(path = "folder.df/")
add_chunk(main.disk.frame, chunk1, chunk_id = "chunk1", compress = 100)
add_chunk(main.disk.frame, chunk2, chunk_id = "chunk2", compress = 100)
```

I now filter the variable `Logical` (boolean) to retrieve only `TRUE` values in both chunks : 

```r
library(data.table)
true <- main.disk.frame[Logical == TRUE]
```

Performing the filtering action with `data.table` will thrown the following error :

```r
Error in rbindlist(res, use.names = use.names, fill = fill, idcol = idcol) : 
  Column 4 ['Character'] of item 2 is missing in item 1. Use fill=TRUE to fill with NA (NULL for list columns), or use.names=FALSE to ignore column names.
```

However, if a perform the same action using `dyplr`, I will get the result without any error :

```r
library(dplyr)
true <- main.disk.frame %>% filter(Logical == TRUE) %>% collect()
```

I am wondering if it would be possible to fix this issue by adding `fill=TRUE` in the `rbindlist` used by data.table to perform the filtering (or any other function).

Thanks.

**Comment by xiaodaigh** [comment] 2020-07-09 08:29
Thanks for the bug report.

Yeah, as you saw `data.table` isn't well support at this stage. I think I should add that to the rbindlist. But in general working on chunks that have different columns are dangerous. I think seriously thinking about adding a `force = TRUE` to `add_chunk` and allow `add_chunk` to fail if there is a column mismatch.

**Comment by xiaodaigh** [comment] 2020-07-09 08:34
The solution fo now is to use the `fill=TRUE` explicitly.

Technically this is not a bug :)

```
true <- main.disk.frame[Logical == TRUE, fill= TRUE, use.names = TRUE]
```

See 

```
?`[.disk.frame`
```

![image](https://user-images.githubusercontent.com/4497189/87017047-d5c6d900-c212-11ea-8d94-7da6ec151a96.png)


I will close it for now. Thanks for your bug report.

**Closed by xiaodaigh** 2020-07-09 08:34 UTC

**Comment by palamito** [comment] 2020-07-09 10:09
Thanks a lot @xiaodaigh and sorry for this improper bug report.

I understand your point, but please keep the option `fill=TRUE` available since it may be very useful (although not always good practice).

Thanks.

**Comment by xiaodaigh** [comment] 2020-07-09 10:40
Yeah. Need to think a about API.
