### ISSUE TITLE
Select() + mutate_all() throws error

### ISSUE THREAD

**Issue by caewok** [xiaodaigh/disk.frame#208] opened 2019-11-15 21:19 UTC
Running dplyr::select followed by dplyr::summarize_all returns an error that it cannot find a column, presumably because the select function is not correctly limiting the columns passed to the summarize function. For example, this code fails:

```
mtcars.df <- as.disk.frame(mtcars, nchunks = 3)
sums <- mtcars.df %>%
  dplyr::select(mpg, cyl, hp) %>%
  dplyr::mutate_all(sum) %>%
  collect 
# Error: object 'disp' not found

```
As `disp` is the first column removed by the select function, I assume the problem is with how select is interacting with the mutate_all.

**Comment by xiaodaigh** [comment] 2019-11-16 03:44
The issue is that `dplyr` doesn't make `mutate_all` into an S3 method like `mutate` see https://github.com/tidyverse/dplyr/issues/4541

So `dplyr::mutate_all` doesn't work for `disk.frame`s but there is a `disk.frame::mutate_all.disk.frame`. As soon as `dplyr` makes `mutate_all` an S3 function, then your code would work. 

But for now, the ugly workaround now is 

```r
mtcars.df <- as.disk.frame(mtcars, nchunks = 3)
sums <- mtcars.df %>%
  dplyr::select(mpg, cyl, hp) %>%
  disk.frame::mutate_all.disk.frame(sum) %>%
  collect 
```

I don't wish to make `disk.frame` overwrites the `dplyr` function. Instead, I would much prefer dplyr to do that.

I will close this for now. The compromise I am willing to make is the possibility of a `disk.frame:::dplyr_compat()` which when run will overwrite the `mutate_all` functions and make it S3 compatible, but I am not sure if that's aligned with CRAN policies.

**Closed by xiaodaigh** 2019-11-16 03:44 UTC
Labels: have work around, question, ux, wontfix
