### ISSUE TITLE
simple interface to shard an existing disk.frame by a different (non-nested) variable

### ISSUE THREAD

**Issue by kendonB** [xiaodaigh/disk.frame#154] opened 2019-09-08 01:50 UTC
I have a case where in some operations I need a disk.frame sharded in one dimension and in other operations I need it sharded in another. It would be neat if there was a nice memory-efficient way to shard an existing disk.frame into another dimension.

I tried the below which doesn't successfully shard the second df at all:

```` r
library(disk.frame)
mtcars_df = as.disk.frame(mtcars, outdir = "mt_shard_by_cyl", shardby = "cyl", overwrite = TRUE)
mtcars_df_2 = write_disk.frame(mtcars_df, outdir = "mt_shard_by_gear", shardby = "gear", overwrite = TRUE)
list.files("mt_shard_by_gear", full.names = TRUE) %>% 
  map(fst::read_fst)
#> [[1]]
#>    mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> 1 21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
#> 2 21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
#> 3 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
#> 4 18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
#> 5 19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
#> 6 17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
#> 7 19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
#> 
#> [[2]]
#>     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> 1  18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
#> 2  14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
#> 3  16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
#> 4  17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
#> 5  15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
#> 6  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
#> 7  10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
#> 8  14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
#> 9  15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
#> 10 15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
#> 11 13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
#> 12 19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
#> 13 15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
#> 14 15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
#> 
#> [[3]]
#>     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> 1  22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> 2  24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
#> 3  22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
#> 4  32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
#> 5  30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
#> 6  33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
#> 7  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
#> 8  27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
#> 9  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
#> 10 30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
#> 11 21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
````

<sup>Created on 2019-09-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The algorithm would have to go something like:
1. Read in the unique values of the sharding variables from all chunks
2. choose the chunks in some sensible way
3. read and rewrite the data required for _each new_ chunk for _all existing chunks_, one new chunk at a time.

**Comment by xiaodaigh** [comment] 2019-09-08 02:10
Thanks for the report. I will prioritise this. Thanks for your understanding that disk.frame is at 0.1.0 so plenty of bugs are expected. Please be patient while I look into this.

In the mean time, did_ you know that you that collecting the chunks as lists can be accomplished using existing disk.frame functions?
  
  ````r
mtcars_df_2 %>%
  collect_list

mtcars_df_2 %>%
  map(~.x, lazy = F)

mtcars_df_2 %>%
  map(~.x) %>%
  collect

mtcars_df_2 %>%
  map(I, lazy = F)
```

so you don't need to do to save some typing

```r
list.files("mt_shard_by_gear", full.names = TRUE) %>% 
  map(fst::read_fst)
```

**Comment by xiaodaigh** [comment] 2019-09-08 04:13
Your particular example should work now with the latest version on github, fixed by #155 

```r
# install latest
devtools::install_github("xiaodaigh/disk.frame")
library(disk.frame)

# setup disk.frame with multiple workers
setup_disk.frame()

mtcars_df = as.disk.frame(mtcars, outdir = "mt_shard_by_cyl", shardby = "cyl", overwrite = TRUE)
mtcars_df %>% 
  collect_list

mtcars_df_2 = write_disk.frame(mtcars_df, outdir = "mt_shard_by_gear", shardby = "gear", overwrite = TRUE)

mtcars_df_2 %>% 
  collect_list
```


**General re-sharding**

As regards to quickly re-sharding, there are some functions in disk.frame to help with that already. But the problem is that they are VERY slow, as they involve reorganising chunks on disk. So they should be avoided. I would encourage you to find a solution that doesn't involve `hard_group_by` or re-sharding! For example, `write_disk.frame(...., shardby = "new_shard_key", ...)` is VERY slow!

 but if you really need to, you can use `hard_group_by` which works like this

```r
mtcars_df_2 = mtcars_df %>% 
  hard_group_by("gear", outdir = "somewhere_new_or_defaults_to_tempfile")

mtcars_df_2 %>% collect_list
```

It so happens that all `gear` end up in the same chunk`, try this and you shall see that therea re more chunks

```r
mtcars_df %>% 
  hard_group_by("hp", outdir = "plsdel") %>% 
  collect_list
```

If you like, you can open up an issue with the actual use-case, and I can see if disk.frame can support that or if I know of a way to accomplish that with disk.frame in an efficient manner.

**Comment by kendonB** [comment] 2019-09-08 04:15
I'm not worried about the initial round of sharding being slow as it's just an initial processing stage. I will try these out soon. Cheers

**Comment by xiaodaigh** [comment] 2019-10-16 12:45
I will close this now as I assume disk.frame can handle your user case now. Feel free to re-open if anything is amiss

**Closed by xiaodaigh** 2019-10-16 12:45 UTC
Labels: bug, enhancement, question, ux
